# Common for all services
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0  # Captures 100% of requests (use 0.1 in production)
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
      
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
