# Common for all services
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
