# Unique to Auth Service
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: Chandan
    password: Chandan@23
  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitkumar231062@gmail.com
    password: omul qczy mjem mevs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /auth/v3/api-docs 
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: /
